### ISSUE TITLE
Support field tag to prevent Wire filling in struct fields

### ISSUE THREAD

**Issue by zombiezen** [google/wire#110]
### Is your feature request related to a problem? Please describe.

Like in #36, it would be nice to restrict Wire from filling in certain fields. Sometimes it's useful to specify these rules from the provider set side, and other times it's useful to specify these rules closer to the struct definition.

### Describe the solution you'd like

I'd like to be able to add a struct tag like `wire:"-"`:

```go
type Foo struct {
  mu  sync.Mutex  `wire:"-"`
  Bar Bar
}
```

When adding `Foo{}` to a provider set.

### Describe alternatives you've considered

The solution I suggested in [this comment](https://github.com/google/wire/issues/36#issuecomment-429422710) is useful in circumstances where a fixed set of fields should be filled in, but not in ones where I want most fields to be filled in with some exceptions. The approach here also gives more tooling safety: instead of naming a field this attaches the information directly to the field. The downside is that this becomes awkward if someone has a legitimate need to fill in a field in a Wire provider set.

**Comment by myyk** [comment]
Should this be closed? A change has been merged to address the issue.

**Comment by zombiezen** [comment]
@shantuo, are we still waiting for a doc change here?

**Comment by shantuo** [comment]
That's correct, I'm going to add it to the guide.
