### ISSUE TITLE
wire: improve error message when a provider set includes a binding but not the corresponding concrete type

### ISSUE THREAD

**Issue by jarollz** [google/wire#113]
### Describe the bug

A wire set containing __subsets__ (one or more wire sets), should be just the same as a wire set with items from that subsets added directly.

### To Reproduce

Given this code:

__master.go__
```go
package wirebug

type ISomeInterface interface {
	DoStuff(thing string) int
}

type SomeStuff struct{}

func (si *SomeStuff) DoStuff(thing string) int {
	return len(thing)
}

func NewStuff() *SomeStuff {
	return &SomeStuff{}
}
```

__wiring.go__
```go
package wirebug

import "github.com/google/wire"

var WiringProviders = wire.NewSet(
	NewStuff,
)

var WiringBindings = wire.NewSet(
	wire.Bind(new(ISomeInterface), new(SomeStuff)),
)

var WiringSet = wire.NewSet(
	WiringProviders,
	WiringBindings,
)
```

__injectors.go__
```go
//+build wireinject

package wirebug

import "github.com/google/wire"

func InjectStuff() ISomeInterface {
	wire.Build(WiringSet)
	return nil
}
```

Running `wire ./...` results in an error:
```
$$$/wirebug/wiring.go:10:2: no binding for *$$$/wirebug.SomeStuff
wire: at least one generate failure
```
It's as if items from `WiringProviders` can't be seen by `WiringBindings` although they're inside `WiringSet`. Inside the documentation of `wire.NewSet`, there's this statement, **"Passing a ProviderSet to NewSet is the same as if the set's contents were passed as arguments to NewSet directly."**, but it turns out that it's not so.

## Expected behavior

The file `wire_gen.go` should be generated without problem.

Both of these `WiringSet`
```go
var WiringProviders = wire.NewSet(
	NewStuff,
)

var WiringBindings = wire.NewSet(
	wire.Bind(new(ISomeInterface), new(SomeStuff)),
)

var WiringSet = wire.NewSet(
	WiringProviders,
	WiringBindings,
)
```
and
```go
var WiringSet = wire.NewSet(
	NewStuff,
	wire.Bind(new(ISomeInterface), new(SomeStuff)),
)
```
should behave the same. But only the below version works.

### Version

Version 0.2.1

### Additional context

None.

**Comment by vangent** [comment]
A very subtle line in the user guide states "Any set that includes an interface binding must also have a provider in the same set that provides the concrete type."

So, your `WiringBindings` provider set is invalid. Our error message here is very poor, and we'll take this bug to make it more obvious.

**Comment by jarollz** [comment]
@vangent: Thanks for making it clearer. However, maybe in the future there could be something like `wire.NewSubSet`, so that we can reuse/mix-match some binding subsets with some other provider subsets into a new set. In my case it's something like:

```go
// define the wiring subsets...
var BindingsSubset = wire.NewSubSet(...);
var RealProviders = wire.NewSubSet(...);
var MockProviders = wire.NewSubSet(...);

// define the wiring sets for injectors...
var RealSet = wire.NewSet(BindingsSubset, RealProviders);
var MockSet = wire.NewSet(BindingsSubset, MockProviders);
```

**Comment by jarollz** [comment]
`BindingsSubset` binds from interfaces to structs which can be provided by both `RealProviders` and `MockProviders`.

**Comment by vangent** [comment]
OK. If there are types that are in both `RealProviders` and `MockProviders`, then put them in their own set:

```
var CommonProviders = wire.NewSubSet(...);  // including bindings
var RealProviders = wire.NewSubSet(...);    // including bindings
var MockProviders = wire.NewSubSet(...);    // including bindings

var RealSet = wire.NewSet(CommonProviders, RealProviders);
var MockSet = wire.NewSet(CommonProviders, MockProviders);
```

**Comment by jarollz** [comment]
To clarify, what I have in mind is to prevent something like this:
```go
var RealProviders = wire.NewSet(
    wire.Bind(new(IfaceA), new(SomeStruct),
    ctors.NewSomeStruct,
);

var MockProviders = wire.NewSet(
    wire.Bind(new(IfaceA), new(SomeStruct),
    ctors.NewSomeStructMock,
);
```
As can be seen, the `wire.Bind` is the same, but needed to be written twice. That's why I imagine something like `wire.NewSubSet` that is just used to collect bindings, providers, etc which can't be used directly by `wire.Build`, but then can be composed into one through `wire.NewSet` which then run the checks that all bindings must have providers, etc.

**Comment by vangent** [comment]
Why does `MockProviders` add a binding for `SomeStruct` when it's providing a `SomeStructMock`? It seems like it should be

```go
var MockProviders = wire.NewSet(
    wire.Bind(new(IfaceA), new(SomeStructMock)),
    ctors.NewSomeStructMock,
);
```

Or is `NewSomeStructMock` returning a `SomeStruct`, just using a different constructor? If so, yes, I think you'll just have to repeat the `wire.Bind`.

**Comment by jarollz** [comment]
> Why does `MockProviders` add a binding for `SomeStruct` when it's providing a `SomeStructMock`? It seems like it should be
> 
> ```go
> var MockProviders = wire.NewSet(
>     wire.Bind(new(IfaceA), new(SomeStructMock)),
>     ctors.NewSomeStructMock,
> );
> ```
> 
> Or is `NewSomeStructMock` returning a `SomeStruct`, just using a different constructor? If so, yes, I think you'll just have to repeat the `wire.Bind`.

Yes, `NewSomeStruct` and `NewSomeStructMock` both return the same type `SomeStruct`.
Indeed, it's true as of now (v0.2.1) I'll need to repeat the `wire.Bind`.

I hope something like that new-sub-set can be provided in the future :+1:
