### ISSUE TITLE
Error: unknown pattern

### ISSUE THREAD

**Issue by e-nikolov** [google/wire#144]
If the old imports ("github.com/google/go-cloud/wire") are used for provider sets (probably other things too) with the new binary ("github.com/google/wire"), a very non-descriptive error is shown during generation that just states "unknown pattern". 

Not sure if it is necessary to take any action to improve the error message, but I wanted to make this issue in case anyone else stumbles upon this and maybe save them an hour of debugging.

**Comment by shantuo** [comment]
"unknown pattern" comes from processing the marker functions, I agree we can improve the error message, at least notifying user to update wire when appropriate.

**Comment by zombiezen** [comment]
Thanks for the report; sorry for the debugging woes. This is a known consequence of changes made in #83. Rest assured, we don't plan to change the imports again any time soon.
