### ISSUE TITLE
Wire Launch

### ISSUE THREAD

**Issue by shannontan-bolt** [google/wire#146]
Preface: This is not an issue, but I didn't think the Google groups were the right venue for this discussion. Feel free to punt this elsewhere, etc.

Hey team! We at Bolt are definitely intrigued by this project, and we're sort of charting our migration path forward before we embark on the development work. The large outstanding question at this point is when this project will make it out of alpha, and I'm curious how you're thinking about timelines/the maturity of this project. Are there any timeline goals for the project?

While we'd love to adopt this framework, Facebook's injection is working generally fine for us. Therefore, we can't quite make the case just yet to adopt without it coming out of alpha, but when it does, we'd definitely want to give it a shot.

Thanks! And great work!

**Comment by h7kanna** [comment]
Hi, I have the same issue. I could use Wire successfully in few projects. But I am finding difficult to explain the alpha status of wire to my team.

**Comment by zombiezen** [comment]
Hey folks! Happy to hear the interest. At the moment, we have a few outstanding issues that we want to address before we graduate Wire to beta:

-  **Changes to struct providers:** #36, #32, and #110
-  **Fixing an inconsistency in `wire.Bind`: #120

Once we've fixed those, we are fairly confident we can make future changes in a backward-compatible manner. These changes are fairly minimal, and hopefully there's enough information in those issues that your organizations can plan accordingly. Thus, we would declare Wire as beta and then graduate to 1.0 for a period of time after that.

I don't have an exact timeline we can communicate at the moment, but I would expect beta to come in the next month or so, and 1.0 sometime before end of 2019. Does this address your question?

**Comment by shannontan-bolt** [comment]
@zombiezen Thanks! I appreciate the response, and the transparency. This does address my questions, but I do have one last question.

While I'm sure you can't answer with certainty, is this a project/framework that Google is committed to maintaining in the long run? Is there any dependency on framework usage in the beta version to determine if this will move to 1.0?

**Comment by zombiezen** [comment]
We are not using usage as a measure of 1.0-ness; we are using stability of API as a measure of 1.0-ness. We have every intention of continuing to maintain Wire, as it is a critical piece of infrastructure for the Go CDK.

**Comment by shannontan-bolt** [comment]
Got it - great to know! I'm closing this out and watching the releases. In due time, when the beta comes out, I'm sure we'd love to incorporate and contribute as well. 

Thanks.

**Comment by zombiezen** [comment]
Hey @shannontan-bolt and @h7kanna! If you didn't see, we announced [Wire as beta](https://github.com/google/wire/releases/tag/v0.3.0) last week. Please file issues if you encounter any issues. Cheers!

**Comment by shannontan-bolt** [comment]
@zombiezen - thanks so much!
