### ISSUE TITLE
Can at some point Wire become 'go wire' ?

### ISSUE THREAD

**Issue by h7kanna** [google/wire#150]
Hi, 
Crazy proposal.
Any plans to consider proposing Wire to be part of go toolchain (https://github.com/golang/tools)

I would really like the command. :)
'go wire'

**Comment by zombiezen** [comment]
Hello! We have no such plans. The barrier to entering the standard toolchain/library is pretty high, and it doesn't give Wire any benefits over what it can already do with the source analysis packages in `golang.org/x/tools`, the repository you mention.

If you think Wire would make a good addition to the standard toolchain, the right place to start would be [Go proposal process](https://github.com/golang/proposal).
