### ISSUE TITLE
docs: functions should state clearly where they should be used

### ISSUE THREAD

**Issue by rogpeppe** [google/wire#165]
In the [package documentation](https://godoc.org/github.com/google/wire), some functions (Build, for example) are intended to be used only in wireinject-tagged code, but others (NewSet, for example) are intended to be used in regular Go code.

As the distinction between these two kinds of code is probably the hardest aspect of wire to grasp, the documentation should try to make it very clear which things are expected to be used in which context.

**Comment by vangent** [comment]
@zombiezen can you take a look?

**Comment by zombiezen** [comment]
@rogpeppe, I'm not sure I fully follow how you're making this distinction. IIUC, `wire.Build` is the only such function that needs to be used in a specific place ("wireinject-tagged code") and all the other package functions would be in the other category. The first sentence of `wire.Build`'s godoc currently reads:

> Build is placed in the body of an injector function template to declare the providers to use.

I agree there is room for improvement in the documentation, but I'm not seeing yet how to address the concern you are raising.

**Comment by rogpeppe** [comment]
Yes, I see you're right now. I was originally thinking that more functions would only make sense in wireinject-tagged code, but I see now that NewSet and friends are intended for export.

The thing that's hard to get one's head around is that you have this code in a normal package (e.g. a call to NewSet) that seems to do nothing, but is important anyway. This is where wire starts to feel like "magic".
