### ISSUE TITLE
docs: NewSet doc comment isn't accurate

### ISSUE THREAD

**Issue by rogpeppe** [google/wire#166]
The NewSet doc comment says , "all the parameters must be of non-identical types", but if we've got (say) two calls to Value, two parameters will be of type ProvidedValue, which are both identical types.

Perhaps there's a better way of saying this?

**Comment by vangent** [comment]
In context, the parameters that sentence is referring to are the parameters to a function argument to `NewSet` (not the parameters to `NewSet` itself).

I'll add a word or two to clarify.
