### ISSUE TITLE
Copyright Headers

### ISSUE THREAD

**Issue by poy** [google/wire#168]
### Is your feature request related to a problem? Please describe.

When generating code, it would be helpful if `wire` would also grab the copyright header (or at least offer a way to provide one). Otherwise I have to add one after generating the file.

### Describe the solution you'd like

It would be great if `wire` could grab the header from the file with the injectors.

### Describe alternatives you've considered

Currently, I have to add it manually after running `go generate`

### Additional context

Internal tools require the header. Other generators (e.g., k8s.io/code-generator and github.com/golang/mock) have similar features.

**Comment by vangent** [comment]
There's not necessarily a single file with injectors, is there? For example, https://github.com/google/go-cloud/tree/master/samples/guestbook has multiple `_inject.go` files but a single `wire_gen.go`.

Could you provide more specific links to how those other generators accomplish this?

It looks like `github.com/golang/mock` ([link](https://github.com/golang/mock)) uses a `--copyright_file` argument to the binary, which it presumably prepends to what it is going to output.

@zombiezen thoughts on this?

**Comment by zombiezen** [comment]
It would be nice if Wire could detect this just from the source files, but a `--copyright_file` flag would be a pretty reasonable way to go.

I also wonder if an option to send generated code to stdout would be okay: then you could have Wire in a pipeline with `cat`.

**Comment by poy** [comment]
@vangent  k8s.io/code-generator has this: https://github.com/kubernetes/code-generator/blob/e797d15e3d1a5372a1ffa022df4f17dc93adc584/cmd/go-to-protobuf/protobuf/cmd.go#L90 (`--go-header-file`)

**Comment by eliben** [comment]
A slightly more general approach would be to use a template file with some sort of ``{{generate file here}}`` marker and whatever the user wants around it

**Comment by vangent** [comment]
I'll try adding a command-line flag.
