### ISSUE TITLE
Struct not declared by package wire

### ISSUE THREAD

**Issue by euclid1990** [google/wire#176]
Hello everyone
I using wire for DI in my project, my code is following:

```
func NewContainer() (*services.Container, error) {
	containerSet := wire.NewSet(
		wire.Struct(new(services.Container), "Country"),
	)
	wire.Build(containerSet)
	return &services.Container{}, nil
}
```

But, when I run command:
```
$ wire
```
It output this error:
```
... Struct not declared by package wire
```
Maybe this line: "wire.Struct(new(services.Container), "Country"),"

Anyone can help me slove this issue ? It seem like wire v0.2.2 does not support `Struct` method ?

my `go.mod`
```
module mprof

go 1.12

require (
	github.com/Masterminds/squirrel v1.1.0
	github.com/go-sql-driver/mysql v1.4.1
	github.com/google/go-cmp v0.3.0 // indirect
	github.com/google/wire v0.2.2
	github.com/jinzhu/gorm v1.9.4
	github.com/spf13/cobra v0.0.3
	github.com/spf13/viper v1.3.2
	go.uber.org/atomic v1.3.2 // indirect
	go.uber.org/multierr v1.1.0 // indirect
	go.uber.org/zap v1.10.0
	golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f // indirect
	golang.org/x/net v0.0.0-20190509222800-a4d6f7feada5 // indirect
	golang.org/x/sys v0.0.0-20190509141414-a5b02f93d862 // indirect
	golang.org/x/text v0.3.2 // indirect
	golang.org/x/tools v0.0.0-20190513233021-7d589f28aaf4 // indirect
)
```

The same example : https://github.com/google/wire/blob/master/docs/guide.md#struct-providers also output similar error !

**Comment by shantuo** [comment]
Hi, `Struct` is a new feature that is not included in v0.2.2. It will be in the next release. You would need to use master for now if you want to use it.

**Comment by vangent** [comment]
@euclid1990 -- you can wait until the next release (should be in the next week or two), or until then you can update your `go.mod` file to request a [pseudo-version](https://golang.org/cmd/go/#hdr-Pseudo_versions). For example, something like `go get github.com/google/wire@d76a979` should do it.

**Comment by euclid1990** [comment]
@shantuo Ok, thank you for your answer!
@vangent Thank you for your solution, I will try it 👍 ro
