### ISSUE TITLE
how to use the _tutoria demo 'correctly'?

### ISSUE THREAD

**Issue by orichi** [google/wire#178]
Hello. I am learning wire.
I tried to run the [demo](https://github.com/google/wire/tree/master/_tutoria) project locally, I have executed wire and generated the wire_gen.go file. When I executed go run main.go, I got an error.
wires/wire_gen.go:10:6: InitializeEvent redeclared in this block
        previous declaration at wires/wire.go:11:45

No error occurred when executing `go run --tags=wireinject main.go`, but no results returns.
How to execute the “correct” command to get the correct result?

**Comment by vangent** [comment]
Hi, thanks for checking out Wire!

Did you add the `//+build wireinject` line, followed by a blank line, in your `wire.go`? That should make it so that `go build` / `go run` don't try to compile that file.

If that doesn't solve your problem, can you paste or attach your `wire.go` file?

**Comment by vangent** [comment]
Ping @orichi? I'm going to go ahead and close this issue if I don't hear back.

**Comment by worming004** [comment]
I encountered the same issue. For the one who also reach this issue, be aware that line `//+build wireinject` have to be the very first line of the file, above the package. And as @vangent  explain, do not forget the blank line between this comment line and package.
This solution work for me

**Comment by Selion05** [comment]
I had a simliar issue. I used `go build cmd/server/*.go` which used shell file matching. A working example would be `go build ./cmd/server`.
Note that you need to use explicitly relative paths because `go build cmd/server` also yields an error ( package cmd/server is not in GOROOT )
