### ISSUE TITLE
wire.NewSet does not generate any code in the wire_gen.go file

### ISSUE THREAD

**Issue by zombiezen** [google/wire#182]
From @GarimaBathla on golang/go#32217:

> #### What did you do?
> I am trying to use wire. 
> 
> wire command generates some code but not complete code. 
> all providers with wire.build get generated correctly in generated code. 
> but function that provides are wire.NewSet (provider set) is not getting generated code. 
> 
> #### What did you expect to see?
> I expect to see that either wire will give an exception on why wire.NewSet is not getting resolved.
> 
> #### What did you see instead?
> No exception. just generated code has 2 sections.. 
> // Injectors
> And
> // file.go
> with function with wire.NewSet
> 
> func ProvideClients(configFilePath string) (error, *dsc.Client, *dsc.NCFile) {
> 	initLogger()
> 	wire.NewSet(provideConfig, provideSSHClient, provideCMDExecutorInstance, provideDSCClient, provideNCFileClient)
> 	return nil, nil, nil
> }
> 
> 
> 1) Am I missing something here, not much info on provider sets code generation online
> 2) And also running go generate doesn't really generate any wire code? is it suppose to?
> #### Does this issue reproduce with the latest release (go1.12.5)?
> Haven't tried.
> 
> #### System details
> 
> ```
> go version go1.12.4 darwin/amd64
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/gb186037/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/gb186037/Projects/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> GOROOT/bin/go version: go version go1.12.4 darwin/amd64
> GOROOT/bin/go tool compile -V: compile version go1.12.4
> uname -v: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
> ProductName:	Mac OS X
> ProductVersion:	10.12.6
> BuildVersion:	16G29
> lldb --version: lldb-900.0.45
>   Swift-4.0
> ```

**Comment by vangent** [comment]
Hi @GarimaBathla,

Only `wire.Build` will result in `wire` generating code. A `ProviderSet` is just a way to group provider functions that are often used together.

For example, assume that `func Foo() *Foo` is a provider function that provides a `*Foo`, and that `func Bar(foo *Foo) *Bar` is a provider function that provides a `*Bar` given a `*Foo`. You could write an injector function with `wire.Build`:

```
func injector() *Bar {
  wire.Build(Foo, Bar)
  return nil
}
```

and `wire` will generate code for that for you.

Alternatively, you could create a `ProviderSet` like `var FooAndBar = wire.NewSet(Foo, Bar)` and change your injector to:

```
func injector() *Bar {
  wire.Build(FooAndBar)
  return nil
}
```

and `wire` will generate the exact same code as before. In fact, internally the arguments to `wire.Build` [define](https://github.com/google/wire/blob/master/docs/guide.md#injectors) a `ProviderSet`.



In your code snippet, it looks like you want `ProvideClients` to be an injector function, so you should use `wire.Build` in it. You can either list all of the providers needed separately, or create a `wire.NewSet` with them and reference the set, like `FooAndBar` above. The latter probably only makes sense if you're going to use the set somewhere else in your program.

Other notes:
* The error should be the last return value from your injector function (not the first one). This is common for Go usage, and `wire` also assumes this when handling errors from providers.
* You can't put anything other than `wire.Build` and the `return` in an injector, so you should move the `initLogger` call to the code that calls `ProvideClients`.

**Comment by GarimaBathla** [comment]
@vangent Thanks! makes sense.

I had wire.Build in individual provider functions.. but my main function ProvideClients that actually wires everything together I only had wire.NewSet - I should have wire.Build of wire.NewSet to get it resolved. Thanks!!
