### ISSUE TITLE
Providers from interfaces?

### ISSUE THREAD

**Issue by srenatus** [google/wire#187]
### Describe the bug

When using `wire` on the following example code, it will fail:

### To Reproduce

```go
package main

import "github.com/google/wire"

type Thing struct{}

type Fooer interface {
	MakeThing() Thing
}

type foo struct{}

func (*foo) MakeThing() Thing {
	return Thing{}
}

func NewFoo() *foo {
	return &foo{}
}

func Init() (Thing, error) {
	wire.Build(
		NewFoo,
		wire.Bind(new(Fooer), new(*foo)),
	)
	return Thing{}, nil
}
```
...with
```
wire: /Users/stephan/go/src/github.com/srenatus/wire-example/wire.go:21:1: inject Init: no provider found for github.com/srenatus/wire-example.Thing, output of injector
wire: github.com/srenatus/wire-example: generate failed
wire: at least one generate failure
```

## Expected behavior

It would have been nice if `wire` had figured out that the `Fooer` interface has a provider for `Thing`. **Alternatively**, there might just be something I've missed -- What do I need to add to the `wire.Build` call to make this work? 😃 

### Version

- master as of yesterday, ed1f30e1e8cc03225f15f4bb986f870c4c6dd394

### Additional context
<details><summary>System details</summary>

```
go version go1.11.3 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stephan/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/stephan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11.3 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.11.3
uname -v: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
lldb --version: lldb-1001.0.13.3
  Swift-5.0
```
</details>

**Comment by vangent** [comment]
I think you can get this to work by adding a new provider for `Thing` given a `Fooer`:

```
func MakeThing(f Fooer) Thing {
  return f.MakeThing()
}
```

I don't think it's feasible to treat all interface methods (or, more broadly, all methods) as providers. They are too likely to conflict (e.g., two methods that both return `string`).

**Comment by srenatus** [comment]
> I don't think it's feasible to treat all interface methods (or, more broadly, all methods) as providers. 

Is this so dissimilar from the struct case? Where either any selected struct field (or "*", all of them) can be marked as providers?

Just wondering 😃

**Comment by vangent** [comment]
Ah, I forgot we added `FieldsOf`. @shantuo / @zombiezen care to comment about whether it would be feasible to do something similar for interfaces?

**Comment by rogpeppe** [comment]
I think this case would probably be covered by #7 - you could add `Fooer.MakeThing` to the `Build` call and it would act as a suitable function for making a Thing given a Fooer.

This is arguably related to a case I've been thinking about: function-valued field values as providers, but I think that's enough different that I'm going to raise another issue for that.

**Comment by zombiezen** [comment]
I agree with @rogpeppe: #7 is the right fix for this. Interface methods are valid for [method expressions](https://golang.org/ref/spec#Method_expressions), so the `wire.Build` call in the above example would become:

```go
wire.Build(
  NewFoo,
  wire.Bind(new(Fooer), new(*foo)),
  Fooer.MakeThing,
)
```

**Comment by srenatus** [comment]
Thanks! Closing in favor of #7 then.
