### ISSUE TITLE
wire: support function-typed struct fields as providers

### ISSUE THREAD

**Issue by rogpeppe** [google/wire#188]
Currently, we can use FieldsOf to use field values directly as providers, but there's no way AFAICS to use function-typed fields as providers.

For example, this doesn't work:

```
package main

type Thing struct{}

type Fooer struct {
	MakeThing func() Thing
}

var fooer = Fooer{
	MakeThing: func() Thing {
		return Thing{}
	},
}

func Init() (Thing, error) {
	panic(wire.Build(
		wire.Value(fooer),
		wire.FieldsOf(new(Fooer), "MakeThing"),
	))
}
```

We probably don't want `FieldsOf` to support this non-explicitly, because function values are perfectly good types in themselves, but perhaps a separate wire function might work; say `FuncFieldsOf` or `ProviderFieldsOf`.

**Comment by shantuo** [comment]
This changes the semantics of `FieldsOf` and add complexity. Maybe once we get to #184 it will make this use case easy and straightforward enough? Closing this, but feel free to reopen it for further discussion.

**Comment by rogpeppe** [comment]
Yes, #184 would make this a little easier because you could do:

     panic(wire.Build(
          wire.Value(fooer),
          wire.FieldsOf(new(Fooer), "MakeThing"),
          func(f func() Thing) Thing {
               return f()
          },
      ))

but this could end up fairly repetitive when there are many such fields.
