### ISSUE TITLE
wire: consider dropping color support in "show"

### ISSUE THREAD

**Issue by vangent** [google/wire#189]
It pulls in several dependencies, and doesn't seem that necessary.

@zombiezen thoughts?

**Comment by zombiezen** [comment]
I do like the feature (in that it does make the output significantly easier to scan), but I don't think it outweighs the dependency bloat. The functionality isn't super hard to replicate, could we just roll back the change to use fatih/color?

**Comment by rogpeppe** [comment]
Another possibility might be to have a way of producing HTML output or similar.

**Comment by vangent** [comment]
I will roll back the change to use `fatih/color`.

I think I'd prefer to remove color entirely rather than try to get color working well (i.e., on Windows, and depending on the terminal).
