### ISSUE TITLE
wire: specify output file to generator 

### ISSUE THREAD

**Issue by myyk** [google/wire#192]
I would like to be able to generate wire files to something not called `wire_gen.go`. In my code base the convention for generated files is `z_foo.go`, so being able to specify the name would give me flexibility without extra commands to move the file after generation each time.

If the generator could be run with an extra argument like `-o z_wire.go` which would put the file in the same directory as the input `wire.go` that would work for me.

Other alternatives may be to use something like a `--prefix "z_"` argument.

**Comment by shantuo** [comment]
Thanks @myyk for the feature request! This is definitely useful. However, `-o` might not be feasible if wire is generating more than one files (when there is injector in the test files). `--prefix` might be the way to go.

**Comment by A-caibird** [comment]
> Fixed with PR #213, thanks for the contribution! Use `--output_file_prefix`.

can you give a full command example,

**Comment by A-caibird** [comment]
> > Fixed with PR #213, thanks for the contribution! Use `--output_file_prefix`.
> 
> can you give a full command example,

wire gen  -output_file_prefix  a
