### ISSUE TITLE
unsupported version of go?

### ISSUE THREAD

**Issue by busgo** [google/wire#194]
wire: unsupported version of go: exit status 2: flag provided but not defined: -compiled
        usage: list [-e] [-f format] [-json] [build flags] [packages]
        Run 'go help list' for details.

--------------------------------------------

appledeMacBook-Pro:_tutorial apple$ wire
wire: unsupported version of go: exit status 2: flag provided but not defined: -compiled
        usage: list [-e] [-f format] [-json] [build flags] [packages]
        Run 'go help list' for details.
        
wire: generate failed
appledeMacBook-Pro:_tutorial apple$ wire wire.go 
wire: unsupported version of go: exit status 2: flag provided but not defined: -compiled
        usage: list [-e] [-f format] [-json] [build flags] [packages]
        Run 'go help list' for details.
        
wire: generate failed
appledeMacBook-Pro:_tutorial apple$

env 

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/Desktop/wp/code/home/go"
GORACE=""
GOROOT="/Users/apple/Desktop/wp/soft/go"
GOTMPDIR=""
GOTOOLDIR="/Users/apple/Desktop/wp/soft/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6j/b2rtjxf17mv6jgvtcy_f31nc0000gn/T/go-build754701190=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by vangent** [comment]
`go version` ?

Does `go build` work?

**Comment by busgo** [comment]
appledeMacBook-Pro:_tutorial apple$ ls
README.md       _tutorial       main.go         wire.go         wire_gen.go
appledeMacBook-Pro:_tutorial apple$ wire
wire: unsupported version of go: exit status 2: flag provided but not defined: -compiled
        usage: list [-e] [-f format] [-json] [build flags] [packages]
        Run 'go help list' for details.
        
wire: generate failed
appledeMacBook-Pro:_tutorial apple$ go version
go version go1.10 darwin/amd64
appledeMacBook-Pro:_tutorial apple$

**Comment by vangent** [comment]
It looks like you are using `go 1.10`. The current stable version is `go 1.12`; I suspect that the library that `wire` uses to do code analysis (`golang.org/x/tools`) only supports the latest stable version and the previous one.

Try updating to a more recent version of `go`....

**Comment by busgo** [comment]
I has give up use  wire !
