### ISSUE TITLE
Cleanup timeouts

### ISSUE THREAD

**Issue by mickeyreiss** [google/wire#200]
## Problem Statement

In production, dependencies can misbehave in unexpected or unchecked ways. For example, a database module could fail to initialize quickly due to network error, or a provider could loop infinitely due to programmer error.

In any case where the particular module is coded to block, rather than fail fast, this can lead to an entire application failing to start up (or shut down) cleanly.

## Potential Solution

I can imagine a number of ways to handle this case, but there is one that seems simple and useful to me: **timeouts**.

If specified in the wireinject code, wire could generate code to perform a timeout on startup (and also during cleanup).

I'm not sure about the syntax, but it could be something like `wire.WithTimeout(SomeProvider, time.Minute)`. It could also be global as a new parameter to `wire.Build`. In either case, the generated code would be surrounded by a select statement that fails when a timer expires.

Does wire's current design already account for this use case? Is it generally programmer error to perform long-running effects in a provider, or are there other legitimate use cases where a provider can fail to return in a timely manner?

**Comment by zombiezen** [comment]
Startup timeouts are already covered by passing a `Context` into the injector function, and we expect this to work today.

Shutdown deadlines are more complex. @rogpeppe and I discussed this in a private thread a little while ago. Paraphrasing his points for posterity:

One could imagine a change to Wire to permit a `Context` being passed to cleanup functions. However, this seems difficult in the general case: if one part of shutdown takes too long and there are chained dependencies to clean up after it, should those other dependencies receive a canceled `Context`?  Even for a single shutdown function, if it's got multiple stages and the first one hangs, should the other stages happen? There's not an obvious answer that's right for all cases.

As you suggest, individual providers could be given a timeout budget for cleanup. However, then the overall timeout could be arbitrarily longer than you specify (consider a situation where any DNS request hangs - every single shutdown function could incur the maximum timeout, and there could be an arbitrary number of places where this happens).

I'm re-titling this issue to reflect the shutdown aspect. At the very least, we should probably add an FAQ entry, but there might be a technical solution.

**Comment by mickeyreiss** [comment]
Thanks for sharing the context, @zombiezen.

> Startup timeouts are already covered by passing a `Context` into the injector function, and we expect this to work today.

We'll go with this pattern for now.

I do think there's something to be said for protecting programmers from error cases: What if a "major" module starts (for example, the API server), but a "minor" one never does (for example, a background job runner) due to a provider silently hanging?

> I'm re-titling this issue to reflect the shutdown aspect. At the very least, we should probably add an FAQ entry, but there might be a technical solution.

Perfect. Thanks for considering the request.  :+1:

**Comment by zombiezen** [comment]
> I do think there's something to be said for protecting programmers from error cases: What if a "major" module starts (for example, the API server), but a "minor" one never does (for example, a background job runner) due to a provider silently hanging?

From my experience, the best practice here is that servers should start up as quickly as possible (nothing I/O-bound), but report unhealthy in its readiness checks until all critical ("major" in your description) dependencies are available. Requests made to a server before that point will likely error if they depend on critical dependencies or serve degraded results if they depend only on the optional dependencies.

I don't think there's a good way for Wire to "protect programmers": this is an essential complexity of designing a distributed service.
