### ISSUE TITLE
wire: Add wildcard(*) to wire.FieldsOf

### ISSUE THREAD

**Issue by h7kanna** [google/wire#204]
### Is your feature request related to a problem? Please describe.

When many struct fields from a Configuration should be injected into different components, wire.FieldsOf will have a long list of field name strings.

Example:
```go
type Config struct {
	Logger     *logger.Config
	HTTPServer *httpserver.Config
        GRPCServer *grpcserver.Config
}

var configSet = wire.NewSet(
	NewConfig,
	wire.FieldsOf(
		new(*Config),
		"Logger",
		"HTTPServer",
                "GRPCServer",
	),
)
```
### Describe the solution you'd like
Provide wildcard convenience.
```go
var configSet = wire.NewSet(
	NewConfig, // Configuration provider
	wire.FieldsOf(new(*Config), "*"),
)
```
This way we can inject configuration easily.

### Describe alternatives you've considered

Use the wire.FieldsOf with list of field strings.

**Comment by vangent** [comment]
A problem with this proposal is that an otherwise backwards-compatible change to the struct can be a breaking change for the Wire set, by adding a new field with a type that's already present in the Wire provider set.

IIUC, that's why we chose to make it explicit which fields of the struct are providers.

**Comment by h7kanna** [comment]
@vangent Yes, it does add breaking change for the wire set. Do you think it is still relevant for config structure which only has unique types as fields? or else I will close this issue.  Thanks

**Comment by vangent** [comment]
If you're guaranteed that your config struct has only unique types as fields, then it would be harder to make a breaking change, but it could still happen; e.g., a `wire.Build` that explicitly includes a `Logger` type, but later the `Logger` type is moved into the `Config` struct.

Unfortunately, we'd either have to add this feature or not.

You can always make a `ProviderSet` that includes all of the fields from the `Config` struct, and include that set elsewhere, so you'll only have to update the list of provided types/fields in one place. The cost of doing so seems pretty low to me, relative to the risk of encouraging users to use a wildcard construct that may cause problems for them later.
