### ISSUE TITLE
How to express conditional dependencies

### ISSUE THREAD

**Issue by djui** [google/wire#205]
This is not an actual feature request, but rather a question how to use Wire with conditional dependencies:

I have a project which loads a configuration and then based on the configuration values, I want to instantiate different implementations (often for the same interface, but sometimes also just create different business logic or even cause side-effects). 

My current best approach is to have an identical dependency tree for all conditional permutations, but that restrict the depth of my dependency tree as as soon as I get in to conditional space, I believe I need to set up the lower tree manually and not via Wire.

One example: Assume we have circuit breaking HTTP client: we would want to wrap on instantiation the default HTTP Client with a caching client, a retry client and a rate limiting client. (`ca(re(ra(c)))`) but all of these only if the configuration states so.

```
.
└── client
    └── rate-limit client
        ├── rate-limit config
        └── retrying client
            ├── retrying config
            ├── IF config.EnableCaching
            │   └── caching client
            │       ├── caching config
            │       └── default client
            └── ELSE
                └── default client
```

What would be a good use here?

**Comment by vangent** [comment]
Since `wire` works via code generation, it doesn't have any explicit support for conditional behavior.

A couple of ideas that might help:

1. You could pass the configuration around everywhere, and apply the conditionals in your provider function(s). For example, if you have a provider that creates your client, it might look something like:

```
func NewClient(cfg *Config) (*Client) {
  client := NewClient()
  if cfg.EnableCaching {
    client = NewCachingClient(client, cfg.CachingConfig())
  }
  client = NewRetryingClient(client, cfg.RetryConfig())
  client = NewRateLimitClient(client, cfg.RateLimitConfig())
  return client
}
```

2. You could always start with the same dependency tree, and then apply changes to it conditionally; something like:

```
client := NewClient(...) // always the same; use wire to generate the code
// Now apply any conditional changes.
if cfg.EnableCaching {
  client = NewCachingClient(client, cfg.CachingConfig())
}
...
```

Hope that helps!

**Comment by djui** [comment]
Thanks for the patterns. I think actually both will be applicable, depending on my use cases.
