### ISSUE TITLE
wire: share dependency graph across injectors in the same package?

### ISSUE THREAD

**Issue by drewolson** [google/wire#21]
I was testing out wire and created a package with two injectors[1]. I noticed that each injector individually recreates the dependency graph. Other DI containers I've used (dagger, for example) allow sharing of singleton objects between different "entry points" to the graph.

Is this behavior intentional or is the goal to eventually allow "reusing" a graph across many injectors within a package?

[1] - https://github.com/drewolson/wiretest/blob/f34107974e871e45ac0f073c7878ab2d6e93b7c4/container/wire_gen.go

**Comment by takanuva15** [comment]
@drewolson I found this issue 5 years later while looking up the same thing - how to share dependencies across injectors (eg reusing one DB connection-pool among multiple DAOs). Unfortunately, the links you posted are dead now and I'm not sure what you're referring to when you mention the "`Options` example".

Could you please share some updated links (or better, sample code) to explain how you managed to share dependencies? Also, what is the "`Options` example" you were referring to?

**Comment by takanuva15** [comment]
After some doing some more research, I found issue #260 where they basically resolve this issue by declaring an `App` super-container struct that has all the top-level dependencies for the application. Then there's only a single injector declared in the `wire.go` file which will naturally reuse all dependencies.

Sample code:
`wire.go`
```go
type App struct {
	*services.AuthService
	*services.FooService
}

var daoSet = wire.NewSet(
	dao.NewAuthDAO,
	dao.NewFooDAO,
)

var svcSet = wire.NewSet(
	services.NewAuthService,
	services.NewFooService,
)

func InitializeApp() *App {
	wire.Build(
		dao.InitDB,
		daoSet,
		svcSet,
		wire.Struct(new(App), "*"),
	)
	return nil
}
```

Then after generating the `wire_gen.go` file by invoking `wire` in the terminal, we can invoke `InitializeApp()` to get the dependencies we need.

For the `Options` stuff, I found this doc page about using an Options struct which is what I assume you were referring to: https://github.com/google/wire/blob/main/docs/best-practices.md#options-structs

```
// A provider function that includes many dependencies can pair the function with an options struct.

type Options struct {
    // Messages is the set of recommended greetings.
    Messages []Message
    // Writer is the location to send greetings. nil goes to stdout.
    Writer io.Writer
}

func NewGreeter(ctx context.Context, opts *Options) (*Greeter, error) {
    // ...
}

var GreeterSet = wire.NewSet(wire.Struct(new(Options), "*"), NewGreeter)
```
