### ISSUE TITLE
Wire 0.3.0 not pass implementations of some interfaces in Bind.

### ISSUE THREAD

**Issue by josgilmo** [google/wire#215]
After the upgrade of the wire library I'm having reported errors that I didn't have in the previous version.

I reproduce the situation and created a small github repository: [https://github.com/josgilmo/wire-issue-214](https://github.com/josgilmo/wire-issue-214)

The error reported by wire it's:

`wire: /Users/josegil/go/src/github.com/josgilmo/wire-issue-214/wire.go:28:2: github.com/josgilmo/wire-issue-214/foo1.MongoGeolocation does not implement github.com/josgilmo/wire-issue-214/foo2.GeolocationReader wire: github.com/josgilmo/wire-issue-214: generate failed wire: at least one generate failure`

I think that the configuration it's valid because wire worked perfect in the tag v0.2.2.

**Comment by vangent** [comment]
This was a breaking change in `v0.3.0`;  see the [release notes](https://github.com/google/wire/releases/tag/v0.3.0), from #120.

"The first argument to wire.Bind is a pointer to a value of the desired interface type and the second argument is a pointer to a value of the type that implements the interface. "

```
wire.Bind(new(foo2.GeolocationReader), new(foo1.MongoGeolocation))
```

and you need

```
wire.Bind(new(foo2.GeolocationReader), &(new(foo1.MongoGeolocation)))
```

HTH

**Comment by josgilmo** [comment]
Thank you very much @vangent! It helps a lot!
