### ISSUE TITLE
Feature request: ignore unused provider set

### ISSUE THREAD

**Issue by titpetric** [google/wire#227]
Currently if a provider set is unused, an error is printed and code generation fails.

~~~
user/wire.go:14:1: inject New: unused provider set "Inject"
~~~

If there is no need to satisfy a structure provided by the set, the code generation could just omit the set either by default or by an extra flag. Not all providers within a set need to be invoked/provide values, so it makes sense that valid providers within a set can be len()==0, not >0

**Comment by titpetric** [comment]
The current work-around is to create a package which merges all your ProviderSets in a single NewSet, code generation does work after that change (but I'd rather drop that package completely).

**Comment by zombiezen** [comment]
Much like Go's general philosophy of erroring for unused variables or imports, this is working as intended in Wire. Partially used sets will not yield errors, but wholly unused sets will.
