### ISSUE TITLE
Update version to v0.3.1

### ISSUE THREAD

**Issue by gilcrest** [google/wire#229]
Not a bug really, but a question - sorry if this is the wrong arena... Wire is currently v0.3.0 and has had 11 commits since this release, most of which are bug fixes. Are you planning to release v0.3.1 any time soon? I know I can get these fixes using modules by deliberately go getting master, but I'm not sure why you're waiting to bump the release to v0.3.1 - are these fixes not release-ready in some way? Are you waiting to bundle a certain number of bugs before release? Sorry for my questions, but I'm just wondering what is the approach for release versioning. 

Thanks for your help! I love wire by the way!

**Comment by zombiezen** [comment]
Thanks for the nudge! We don't have a regular release cadence and we hadn't realized how much had gone in since 0.3.0. [v0.4.0](https://github.com/google/wire/releases/tag/v0.4.0) is ready for download!

**Comment by gilcrest** [comment]
Thanks!
