### ISSUE TITLE
How to inject struct that implements an interface as interface 

### ISSUE THREAD

**Issue by danf0rth** [google/wire#243]
Hi!

```
type User struct{}

type UserRepository interface {
	GetUserByID(ctx context.Context, id int64) (*User, error)
}

func DatabaseBuilder() *sql.DB {
	return nil
}

// Implements UserRepository
type MySQLUserRepository struct {
	db *sql.DB
}

func NewMySQLUserRepository(db *sql.DB) *MySQLUserRepository {
	return &MySQLUserRepository{
		db: db,
	}
}

func (r *MySQLUserRepository) GetUserByID(ctx context.Context, id int64) (*User, error) {
	return nil, nil
}

type Handler struct {
	userRepository UserRepository
}

// Requires interface, but we will provide a struct, that implement this interface
func NewHandler(userRepository UserRepository) *Handler {
	return &Handler{
		userRepository: userRepository,
	}
}

```

How to describe injectors, so that the `NewMySQLUserRepository` will return struct, but this struct will be injected into NewHandler as interface (because it is implementing interface).

I know that i can replace signature of `NewMySQLUserRepository` to `NewMySQLUserRepository(db *sql.DB) UserRepository`, so it will return interface, but this is not always appropriate for me.

I tried `wire.InterfaceValue(new(UserRepository), NewMySQLUserRepository)`, but this will not work, because second argument requires implementation, not injector, so i need to make function call.

**Comment by zombiezen** [comment]
You're looking for [`wire.Bind`](https://pkg.go.dev/github.com/google/wire?tab=doc#Bind):

```go
func inject() *Handler {
  wire.Build(
    DatabaseBuilder,
    NewMySQLUserRepository,
    wire.Bind(new(UserRepository), new(MySQLUserRepository)),
    NewHandler,
  )
  return nil
}
```

**Comment by danf0rth** [comment]
Thanks for your reply, small fix: there must be `*MySQLUserRepository` (pointer to a struct) in a `Bind`, because pointer type implements interface, or you will get error: `MySQLUserRepository does not implement interface UserRepository`

Correct is:
```
...
wire.Bind(new(UserRepository), new(*MySQLUserRepository)),
...
```

**Comment by icamys** [comment]
Alternative to @danf0rth answer is to use a nil instance:

```golang
wire.Bind(new(UserRepository), (**MySQLUserRepository)(nil)),
```
