### ISSUE TITLE
generated functions should copy doc comment from wiregen file

### ISSUE THREAD

**Issue by rogpeppe** [google/wire#244]
The signature and name are generated, but for godoc purposes, the doc comment should be copied too.

**Comment by zombiezen** [comment]
Happy to accept PRs to fix. I'm surprised that you're seeing this, since this is something I was pretty sure Wire was doing properly. Do you have a minimal repro of the issue?

**Comment by rogpeppe** [comment]
Here's a minimal repro of the issue; run it with the [testscript command](https://pkg.go.dev/github.com/rogpeppe/go-internal/cmd/testscript?tab=doc):

```
exec wire
grep 'foobie bletch' wire_gen.go
-- m.go --
package deps

type Foo struct{}

func x() *Foo {
	return new(Foo)
}
-- wire.go --
// +build wireinject

package deps

import "github.com/google/wire"

// NewFoo foobie bletch.
func NewFoo() (*Foo, error) {
	panic(wire.Build(x))
}
-- go.mod --
module m

go 1.14

require github.com/google/wire v0.4.0
```
