### ISSUE TITLE
[QUESTION] How to bind multiple implementations to the same intrerface 

### ISSUE THREAD

**Issue by kpeu3i** [google/wire#246]
I have the following dependencies in my app:

```
type ServoDriver interface {
	Move(angle uint8) error
}

type Robot struct {
	servoX     ServoDriver
	servoY     ServoDriver
}

func NewRobot(servoX ServoDriver, servoY ServoDriver) *Robot {....}

servoX := gpio.NewServoDriver(gopigoDriver, "SERVO_1")
servoY := gpio.NewServoDriver(gopigoDriver, "SERVO_2")
robot := NewRobot(servoX, servoY)
```
Is it possible to inject different multiple implementations (`servoX`, `servoY`) of the same interface (`ServoDriver`) using wire?

**Comment by zombiezen** [comment]
Not directly. See https://github.com/google/wire/blob/master/docs/faq.md#what-if-my-dependency-graph-has-two-dependencies-of-the-same-type

See also: #191 and #207
