### ISSUE TITLE
Question: Is a new instance of a dependency created for each struct that depends on it?

### ISSUE THREAD

**Issue by brpaz** [google/wire#247]
Let´s say I have 3 structs: "Foo", "Bar" and "Baz". 

If "Baz" is a dependency of both "Foo" and "Bar" will be "Baz" be instantiated two times, one in the "Foo" injector and the other in the "Bar" injector?
 
Other languages DI tools, in general, each service is a singleton. I am thinking if that could be a problem or not,  for example, if a specific struct is a dependency of say 10, 20 other structs, as it will be instantiated 20 times.

**Comment by zombiezen** [comment]
Within a given injector function (the generated function), a provider will be called at most once. You can see for yourself by inspecting the generated code.
