### ISSUE TITLE
Question: is it possible to share providers between injectors?

### ISSUE THREAD

**Issue by pablote** [google/wire#253]
I've tried extending the tutorial with a new type "Store" which, like Event(s), have a greeter, they are almost identical. Then I tried adding a new injector, like so:

```go
func InitializeEvent(phrase string) (Event, error) {
	wire.Build(NewEvent, NewGreeter, NewMessage)
	return Event{}, nil
}

func InitializeStore(phrase string) Store {
	wire.Build(NewStore, NewGreeter, NewMessage)
	return Store{}
}
```

And the generated code looks like this:

```go
func InitializeEvent(phrase string) (Event, error) {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event, err := NewEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}

func InitializeStore(phrase string) Store {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	store := NewStore(greeter)
	return store
}
```

Is there any way to have both injectors share the same message and/or greeter? Where I'm going with this is, I'm thinking of Message as my db connection pool, I would like to get different types from the injector, but at the same time, have it only create a single instance of a given type.

Thanks!

**Comment by zombiezen** [comment]
You would need to either pass the message/greeter into the injector or pass in something else that caches the creation of the message/greeter.
