### ISSUE TITLE
Binding one implementation to multiple interfaces

### ISSUE THREAD

**Issue by bench** [google/wire#257]
### Is your feature request related to a problem? Please describe.

I am having little trouble with something that should to be a correct configuration to me.

Frequently, dependency injection is used to bind a concrete implementation for an interface. In my application I follow a well-known package layout in go, which consist in **declaring interfaces in the package where they are used**, and the main package ties together dependencies

Below is my packages structure

```
/config
    /concrete_configuration.go
/api
  /ports.go
  /api1.go
  /api2.go
/db
  /ports.go
  /db1.go
/whatever
  /ports.go
```

Each port file defines its own interfaces, regarding its needs. For instance

`api/ports.go` defines 

```go
type Config interface {
        AppName() string
	BaseAPIRoute() string
}
```

`db/ports.go` defines 

```go
type Config interface {
        AppName() string
	DBConnString() string
}
```

and so on. 

The package `config` provides the implementation that satisfies all those interfaces.

These rules help isolate our packages and define a clear domain language across the entire application. 

Also it makes unit testing very simple with the usage of mocks generated from interfaces.

### What is my issue ?

I hoped to use wire to handle my dependency injections by defining multiple bindings.

```go

var apiSet = wire.NewSet(api.New, config.New,
	wire.Bind(new(api.Config), new(*config.Config)),
)

var dbSet = wire.NewSet(db.New, config.New,
	wire.Bind(new(db.Config), new(*config.Config)),
)

```

but I faced the following error

```
wire: wire.go:33:2: multiple bindings for config.Configuration
        current:
        <- provider "New" (config/config.go:44:6)
        <- provider set "apiSet" (wire.go:21:18)
        previous:
        <- provider "New" (config.go:44:6)
        <- provider set "dbSet" (wire.go:17:17)
```
which means I cannot bind one implementation to multiple interfaces.

### Describe the solution you'd like

Wire does not allow multiple providers for one type to exist in the transitive closure of the providers presented to `wire.Build`

Yet it could support different bindings based on interface/concrete type pair uniqueness.

### Describe alternatives you've considered

I did not find any trade off to help. Ideas are welcome :)

**Comment by zombiezen** [comment]
Wire does act as you describe: it permits a type to be bound to multiple non-identical interfaces. The error message you include is highlighting a different problem: both of your sets include `config.New`, which conflict with each other.

**Comment by bench** [comment]
thank for your quick feedback @zombiezen ! 
Indeed, the error return misled me, sorry for that. :/
You can not use the same constructor in different sets, I imagined duplicated entries would be ignored. 
Wouldnt this be possible ? If so sets could be use to define clearly the list of deps of a constructor.

**Comment by zombiezen** [comment]
See this FAQ: https://github.com/google/wire/blob/master/docs/faq.md#why-does-wire-forbid-including-the-same-provider-multiple-times

**Comment by bench** [comment]
@zombiezen  Roger that and again thanks for your time  
I close this issue.
