### ISSUE TITLE
Command not found: wire

### ISSUE THREAD

**Issue by muhsinshodiq** [google/wire#259]
I just follow your README.md to run this part
```terminal
go get github.com/google/wire/cmd/wire
```
and the result is
```terminal
go: found github.com/google/wire/cmd/wire in github.com/google/wire v0.4.0
```
I create `wire.go` as explained and then try to call `wire` on my terminal and got this result
```terminal
zsh: command not found: wire
```
this is my `$PATH`
```terminal
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
```
and go version that I installed
```terminal
go version go1.14.6 darwin/amd64
```

Can you help me what I'm missing ? thx.

**Comment by mwlazlo** [comment]
Not really a wire problem, but check $HOME/go/bin

**Comment by muhsinshodiq** [comment]
@mwlazlo Just found the issue is because my $GOPATH is empty and on my friend that have expereinced with go help me to solve that.

FYI, I just a new joiner in Go language and when trying to implement other stuff such as echo server, v10 validator never found any issue using go get. Therefore maybe the installation how to part give more explanation about how to get `wire` binary it will be really helpful.
