### ISSUE TITLE
How do I instantiate a dependency only once while injecting?

### ISSUE THREAD

**Issue by bytesmaker** [google/wire#260]
As you can see that [1] is the struct declaration, [2] is my `wire.go` and [3] is the generated file by `wire`.

When I called `ProvideFoo()` and `ProvideBar()` sequentially, `ProvideBaz()` will be called 2 times. It means that in each time *Invoke()* to obtain `Baz`, `Baz` will be re-instantiated but not reuse it which `Baz` was instantiated before. In the same situation, the other DI frameworks e.g `dig`, it will call `ProvideBaz()` only once in whole injection processing. In other words, I expect a provider should only instantiate a dependency only once, and reuse it in whole injection processing. 

Could I do it in `wire`?

I think the mechanism is very useful. If a dependency need to subscribe a message queue while instantiating the dependency, and do something when a specified message arrived, the mechanism ensures that the message queue will only has 1 subscriber. If the dependency would be instantiated once other dependency acquire it, the message queue will have at least 1 subscribers, it will lead system to chaos or error.

Request again, How do I do it?

[1]
![image](https://user-images.githubusercontent.com/67078837/91120965-670de400-e6c9-11ea-87ed-d35aac816c41.png)

[2]
![image](https://user-images.githubusercontent.com/67078837/91120975-6bd29800-e6c9-11ea-8a0d-97034a6416e6.png)

[3]
![image](https://user-images.githubusercontent.com/67078837/91120993-71c87900-e6c9-11ea-9f86-31882f019030.png)

**Comment by vangent** [comment]
Yes, `wire` can handle that. You basically need to make a higher-level injector instead of multiple injectors (for `Foo` and `Bar`) that you call sequentially; `wire` has no way of carrying state between manual calls to two injectors.

By the way, your naming is not quite correct. `wire` calls NewXXX functions "providers"; these are just normal Go functions that create things. The functions that include a call to `wire.Build` are "injectors" (you have named them "ProvideXXX" in your sample code).

One way to do a higher-level injector for your sample code above would be something like this:

```
// Your existing NewFoo, NewBar, NewBaz functions.
...

// A struct that holds all of the things you want wire to create.
// Alternatively, you can define a NewApp provider that takes a Foo and Bar and
// add NewApp to the wire.Build line below instead of the wire.Struct.
type struct App {
  Foo *Foo
  Bar *Bar
}

// An injector for it. You don't need separate injectors for Foo / Bar / Baz.
func initializeApp() (*App, error) {
    wire.Build(NewFoo, NewBar, NewBaz, wire.Struct(new(App), "*"))
    return nil, nil
}
```

HTH

**Comment by bytesmaker** [comment]
Is it mean that I should have a registry table (in your example, it is `App`) to initialize whole dependency graph?

**Comment by vangent** [comment]
Basically, yes. Wire only knows about the things you pass it or that it creates itself. You can either have a single injector function for your whole graph, or you can have multiple injectors but pass things explicitly to them (e.g., if one injector creates a Foo, and there's another injector for Bar, and you want it to use Foo, you need to pass Foo to the injector).

It's pretty common to use a struct like App above to make a root for the dependency graph.

**Comment by bytesmaker** [comment]
I see. Thanks for your help 😄
