### ISSUE TITLE
Make an injector return type optional

### ISSUE THREAD

**Issue by steebchen** [google/wire#263]
### Is your feature request related to a problem? Please describe.

I have various providers which all initialise and clean up things. In theory, I don't need any return value in the injector function.

However, just providing a cleanup function and an error does not work:

```
❯ go run github.com/google/wire/cmd/wire
wire: /Users/luca/projects/ws-api/wire.go:14:1: inject Initialize: no provider found for func(), output of injector
wire: github.com/steebchen/ws-api: generate failed
wire: at least one generate failure
exit status 1
```

### Describe the solution you'd like

An injector function should not require any return value. I'm not sure if this makes sense or if wire needs _some_ entry point, but my thinking is that if I can ignore the first returned value in the main function, it should be optional. I think that would make sense since the main function doesn't really do anything except waiting for signals and is super small, and everything complex is done in each individual package.

### Describe alternatives you've considered

Currently, I just provide some provider and ignore the output result.

### Additional context

This is what my injector function and my main.go look like:

```go
func Initialize() (*server.Server, func(), error) {
	wire.Build(
		prisma.ProviderSet,
		pubsub.ProviderSet,
		api.ProviderSet,
		server.ProviderSet,
	)
	return nil, nil, nil
}
```

```go
func main() {
	_, cleanup, err := Initialize()
	if err != nil {
		panic(err)
	}
	defer cleanup()

	ch := make(chan os.Signal)
	signal.Notify(ch, os.Interrupt, syscall.SIGTERM, syscall.SIGINT)
	<-ch
}
```

The following is what it could maybe look like:

```go
func Initialize() (func(), error) {
	wire.Build(
		prisma.ProviderSet,
		pubsub.ProviderSet,
		api.ProviderSet,
		server.ProviderSet,
	)
	return nil, nil
}
```

```go
func main() {
	cleanup, err := Initialize()
	if err != nil {
		panic(err)
	}
	defer cleanup()

	ch := make(chan os.Signal)
	signal.Notify(ch, os.Interrupt, syscall.SIGTERM, syscall.SIGINT)
	<-ch
}
```

**Comment by zombiezen** [comment]
I can see why you would want such a feature, but this is infeasible to implement. The code generation needs to know what type the injector is trying to resolve. Wire makes an assumption that the first return type is that type, and one would have to introduce another signaling mechanism to indicate what the desired type is. Having to ignore the return value makes it clear to the reader of the code what's going on. Closing.
