### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by insidieux** [google/wire#274]
### Is your feature request related to a problem? Please describe.

This is not a problem. This is just feature request - add official Docker image for wire. 
Most of open source projects have their own official images and possibility to run binary in docker environment. 

### Describe the solution you'd like

Add Dockerfile to repository and build docker image in pipelines for tags.

**Comment by insidieux** [comment]
Hi there
Any updates about this issue? I've also provide pull request here.

**Comment by zombiezen** [comment]
Hey @insidieux, thanks for the suggestion and the PR. While I think having a Docker image can be useful, the bandwidth for us to publish and maintain the image is more than we are willing to take on at this time. If you want to maintain Docker images for Wire, that's great, but we're not looking to upstream this.
