### ISSUE TITLE
Add a convenience function to auto inject all public fields from struct

### ISSUE THREAD

**Issue by h7kanna** [google/wire#286]
### Is your feature request related to a problem? Please describe.

wire.FieldsOf is a useful function to inject Fields from a struct. But it needs all the fields to be explicitly listed. 
If the Struct only has public fields and all of them have to be injected, there should be an easy way to state it.

For example. I have an application that loads config from YAML to Config struct. Its purpose is only a holder of the configuration (loaded from the environment). Initialization looks like below

```
type Config struct {
	App        *app.Config
	Auth       *auth.Config
	Router         *router.Config        
	Logger         *logger.Config
	HTTPServer     *httpserver.Config
}

var New = wire.NewSet(
	LoadConfigFromEnv,
	wire.FieldsOf(
		new(*Config),
		"App",
		"Auth",
		"Logger",
		"HTTPServer",
		"Router",
	),
)
```

### Describe the solution you'd like

Create a public API function wire.AllFieldsOf. So that declaration becomes.

```
var New = wire.NewSet(
	LoadConfigFromEnv,
	wire.AllFieldsOf(new(*Config)),
)
```

or a wildcard field expression like that exists in wire.Struct

```
var New = wire.NewSet(
	LoadConfigFromEnv,
	wire.FieldsOf(new(*Config), "*"),
)
```

### Describe alternatives you've considered

The alternative is of course to list the fields as it is done currently

**Comment by fifsky** [comment]
you can do this
```
var New = wire.NewSet(
	LoadConfigFromEnv,
	wire.Struct(new(*Config),"*"),
)
```

**Comment by h7kanna** [comment]
oh nice, How come I missed it. :( Thanks for your superfast response.

**Comment by h7kanna** [comment]
I get "*" is not a field of struct
wire: at least one generate failure

**Comment by h7kanna** [comment]
Ok, That will not work for the use case I mentioned if I understand correctly.  LoadConfigFromEnv already returns a *Config (from YAML parsing and env). The fields of the Config will provide configuration to different other components. So I want  auto-extract the fields

**Comment by vangent** [comment]
See previous discussion:
https://github.com/google/wire/issues/204

**Comment by h7kanna** [comment]
Duplicate of #204 , I forgot I already requested this.
I guess I am coming to the same pattern. I use wire a lot. Closing this.
