### ISSUE TITLE
cannot find package "." in: when using go generate command while using gomodule

### ISSUE THREAD

**Issue by khanakia** [google/wire#290]
You can use `go bug` to have a cool, automatically filled out bug template, or
fill out the template below.

### Describe the bug

`go generate` command not working

### To Reproduce

* Clone the repo https://github.com/khanakia/gowire/tree/main and run below commands
* `go mod vendor`
* `go generate`

ERROR
```
Lucians-MacBook-Pro:gowire khanakia$ go generate
cannot find package "." in:
	/Volumes/D/www/go1/gowire/vendor/github.com/google/wire/cmd/wire
wire_gen.go:3: running "go": exit status 1
```

## Expected behavior

It should work without any error

### Version

v0.5.0

### Additional context
It works first when i use `wire` command
When using gomodule `go generate` command gives error.

**Comment by SmallTianTian** [comment]
I have the same problem.  It also works by removing `vendor`.

**Comment by khanakia** [comment]
@SmallTianTian i found the solution.
1. You can simply create a new directory in your root director `tools` and  create new file `tools.go` paste the below code
2. Then run `go mod vendor` again and everything will work fine after that.

`tools/tools.go`
```
// +build tools

// tools is a dummy package that will be ignored for builds, but included for dependencies
package tools

import (
  _ "github.com/google/wire/cmd/wire"
)
```

**Comment by SmallTianTian** [comment]
Thank you. Perfect solution to my problem.

Can the authorities do it in a more elegant way?

**Comment by MarsonShine** [comment]
@khanakia thank you，your solution solve my problem
