### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by blank-teer** [google/wire#303]
since April there is a super-useful and relatively small [pull request](https://github.com/google/wire/pull/285) about auto-binding interfaces but it seems to be blocked forever and ever. 

so, is the project dead?

**Comment by eliben** [comment]
I provided some additional details on the linked PR, but in brief: we're fixing bugs, but won't be accepting new features at this time. From our POV, wire is "done". Feel free to fork it to a new project and add any features that seem critical to you.
