### ISSUE TITLE
wire: wire.FieldsOf() to inject the values from fields of a struct

### ISSUE THREAD

**Issue by e-nikolov** [google/wire#32]
Pretty new to wire, so forgive me if I am asking the wrong questions.

As far as I understand, wire.Value() allows to specify a value to be injected. If I have a struct, the fields of which must be injected rather than the value of the struct itself, would I have to use wire.Value() for each field of the struct?

Would it make sense to add something like wire.FieldValues(), which injects the fields of the struct that is specified rather than the struct itself?

**Comment by shantuo** [comment]
Discussed with @zombiezen  offline a bit more. We could add a little bit more of flexibility by matching the "names" of the fields, not types. But the uniqueness of the types that can be used in `FieldsOf` remains unchanged.

```go
package wire

// FieldsOf specifies that the given field names will be provided by extracting them
// from a struct type, which must also be provided in the same provider set. Each
// of the arguments must be a pointer to the type they wish to reference.
//
// For example:
//
//    type S struct {
//        MyFoo *Foo
//    }
//    func NewStruct() *S { /* ... */ }
//    var Set = wire.NewSet(wire.FieldsOf(new(S), "Foo"))
func FieldsOf(structType interface{}, fieldNames ...string) StructFields
```
