### ISSUE TITLE
go get not work with Go 1.17

### ISSUE THREAD

**Issue by jamshidi799** [google/wire#338]
when i try to install wire with this command:
`go get github.com/google/wire/cmd/wire         `  
i get this error:

go get: installing executables with 'go get' in module mode is deprecated.
        To adjust and download dependencies of the current module, use 'go get -d'.
        To install using requirements of the current module, use 'go install'.
        To install ignoring the current module, use 'go install' with a version,
        like 'go install example.com/cmd@latest'.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

base on [this](https://go.dev/doc/go-get-install-deprecation) link, starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.

**Comment by fifsky** [comment]
https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

add file tools.go to Project root

![image](https://user-images.githubusercontent.com/280967/148355866-b7fd0a4a-3431-46f6-89cb-cec88af99a68.png)

**Comment by rsc** [comment]
The right command is now: go install github.com/google/wire/cmd/wire@latest
