### ISSUE TITLE
wire, server: revisit use of wire to fill in all fields of an Options struct

### ISSUE THREAD

**Issue by vangent** [google/wire#36]
server.go has an [Options struct](https://github.com/google/go-cloud/blob/master/server/server.go#L48) with a bunch of exported fields in it.

Today, our examples use wire to fill it in, e.g.:
https://github.com/google/go-cloud/blob/master/samples/guestbook/inject_aws.go#L38

That function returns a *application, which needs a *server.Server, which needs a *server.Options; *server.Options is initialized using the Options{} provider. The generated code is [here](https://github.com/google/go-cloud/blob/master/samples/guestbook/wire_gen.go#L63).

In order to build the struct, wire needs to provide all of the exported fields of the struct.

*  A down side of this is that it's no longer  possible to add a new field to the Options struct without breaking everyone's "go generate". Note that the previously-generated code will work fine, and use the zero value for the new field, but "go generate" will fail because wire will complain it can't find a provider for the new field. 
*  This pattern also only works as long as all of the struct fields have unique types.
*  It also forces the caller to do a somewhat weird incantation using `wire.Bind` if they just want to leave a field nil ([example](https://github.com/google/go-cloud/blob/master/samples/guestbook/inject_local.go#L45)).

1. Could `wire` allow struct providers to leave non-provided fields unset?
2. We could leave `wire` alone, but change the examples to have a newOptions() function that is injected more explicitly.
3. ???

**Comment by shantuo** [comment]
Similar to what we did for `FieldsOf`, I think we could use the field's name instead of type.

```go
package wire

// Struct specifies that the given struct type will be provided by filling in the fields
// in the struct that have the names given. Each of the arguments must be a name
// to the field they wish to reference.
//
// For example:
//
//    type S struct {
//        MyFoo *Foo
//    }
//    var Set = wire.NewSet(wire.Struct(new(S), "Foo"))
func Struct(structType interface{}, fieldNames ...string) StructProvider
```

**Comment by shantuo** [comment]
Documentation also checked in, this is fixed.
