### ISSUE TITLE
Is wire still maintained ?

### ISSUE THREAD

**Issue by khanakia** [google/wire#364]
I see the wire last published [on 26 Jan 2021](https://github.com/google/wire/releases/tag/v0.5.0)

I see many new commits after, so when the new version is planned ?

**Comment by jayzhuang** [comment]
Most of the commits after that date are documentation updates, are there any specific commits that you are interested in?

**Comment by khanakia** [comment]
No particular commit. I just wanted to know that's all

**Comment by calmonr** [comment]
@jayzhuang what about this one? https://github.com/google/wire/pull/353

**Comment by jayzhuang** [comment]
#353 is useful, although I'm not sure whether it warrants a release. Without it, `go run github.com/google/wire/cmd/wire gen` would tell you to `go get github.com/google/wire/cmd/wire`, and after that things would still work correctly, so I'm a bit hesitant to create a release just to pick up this commit.
