### ISSUE TITLE
wire `sync.Map`  throw error

### ISSUE THREAD

**Issue by richenlin** [google/wire#376]
You can use `go bug` to have a cool, automatically filled out bug template, or
fill out the template below.

### Describe the bug

exec: "wire ./..." , not support `sync.Map` , throw error:

```
cannot use (func(key, value interface{}) bool literal) (value of type func(key interface{}, value interface{}) bool) as func(key invalid type, value invalid type) bool value in argument to v.Range

```

### Version

go version: 1.19.2 , wire: v0.5.0

**Comment by liyuliang** [comment]
I have meet the same wrong, does it fix?

**Comment by richenlin** [comment]
fix it:

* remove $GOPATH/bin/wire
* go install github.com/google/wire/cmd/wire@latest
