### ISSUE TITLE
wire: proposal to separate wire into its own module and own repository

### ISSUE THREAD

**Issue by leighmcculloch** [google/wire#49]
#### Go version

```
go version go1.11 linux/amd64
```

#### What did you do?

Add wire as a dependency to a Go project that is using Go modules.

```
$ go get github.com/google/go-cloud/wire/cmd/wire
```

#### What did you expect to see?

Download only `wire` and it's dependencies, which according to the following command, is only two packages (ignoring dependencies within the Go stdlib):

1. `github.com/google/go-cloud/wire/internal/wire`
2. `golang.org/x/tools/go/types/typeutil`

The list of dependencies were determined by running the following command:
```
$ cd $GOPATH/src/github.com/google/go-cloud/wire/cmd/wire
$ go list -f '{{ join .Deps "\n" }}' . | grep '\.'
```

#### What did you see instead?

Go inspecting many packages not used by `wire`.

```
go: finding github.com/google/go-cloud/wire/cmd/wire latest
go: finding github.com/google/go-cloud/wire/cmd latest
go: finding github.com/google/go-cloud/wire latest
go: finding github.com/google/go-cloud v0.2.0
go: downloading github.com/google/go-cloud v0.2.0
go: finding github.com/census-ecosystem/opencensus-go-exporter-aws v0.0.0-20180411051634-41633bc1ff6b
go: finding github.com/dnaeon/go-vcr v0.0.0-20180814043457-aafff18a5cc2
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/GoogleCloudPlatform/cloudsql-proxy v0.0.0-20180321230639-1e456b1c68cb
go: finding github.com/google/martian v2.0.0-beta.2+incompatible
go: finding github.com/gorilla/mux v1.6.1
go: finding github.com/jtolds/gls v0.0.0-20170503224851-77f18212c9c7
go: finding contrib.go.opencensus.io/exporter/stackdriver v0.0.0-20180421005815-665cf5131b71
go: finding gopkg.in/ini.v1 v1.37.0
go: finding cloud.google.com/go v0.0.0-20180816152847-43dc61c3e9d0
go: finding github.com/google/go-cmp v0.2.0
go: finding github.com/smartystreets/assertions v0.0.0-20180301161246-7678a5452ebe
go: finding github.com/aws/aws-xray-sdk-go v1.0.0-rc.5
go: finding golang.org/x/tools v0.0.0-20180314180217-d853e8088c62
go: finding golang.org/x/net v0.0.0-20180702212446-ed29d75add3d
go: go.opencensus.io@v0.12.0: unrecognized import path "go.opencensus.io" (https fetch: Get https://go.opencensus.io?go-get=1: unexpected EOF)
go: finding golang.org/x/crypto v0.0.0-20180718160520-a2144134853f
go: finding google.golang.org/grpc v1.13.0
go: finding github.com/gorilla/context v1.1.1
go: finding google.golang.org/api v0.0.0-20180606215403-8e9de5a6de6d
go: finding github.com/golang/protobuf v1.1.0
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/smartystreets/gunit v0.0.0-20180314194857-6f0d6275bdcd
go: finding gopkg.in/pipe.v2 v2.0.0-20140414041502-3c2ca4d52544
go: finding github.com/aws/aws-sdk-go v1.13.20
go: finding github.com/gopherjs/gopherjs v0.0.0-20180424202546-8dffc02ea1cb
go: finding golang.org/x/oauth2 v0.0.0-20180603041954-1e0a3fa8ba9a
...
```

#### Proposal

It seems that depending on `wire` depends on many other packages because it is contained as part of the large `go-cloud` module, even though `wire` has only two dependencies outside the stdlib.

Even if dependency managers (e.g. `go mod`, `go get`, `dep`, etc) are improved to deal with this situation better and only download the dependencies of the specific package being used, it's overwhelming from a conceptual, external and non-Googler point-of-view to look at this repository for `wire` when this repository is largely not about `wire`.

`wire` appears to be a lightweight, standalone and isolated piece of technology that would be useful to many Go projects that have nothing to do with the cloud, e.g. CLIs. Can it be broken out as a separate module/package?

(If this is not something that is desirable, what are the long term plans for `wire`? Is it intended to become more cloud focused? Should the Go community avoid using it for non-cloud projects?)

**Comment by zombiezen** [comment]
:wave: We've moved! Wire is now its own separate module and repository.

google/go-cloud#828 will track dropping Wire from the Go Cloud repository in a graceful way.

**Comment by leighmcculloch** [comment]
Yay! Fantastic. @zombiezen Thanks!
