### ISSUE TITLE
wire: test flakes on Travis with "failed to cache compiled Go files"

### ISSUE THREAD

**Issue by zombiezen** [google/wire#66]
### Describe the bug

The Wire tests fail intermittently on Travis with an error like:

```
        wire_test.go:96: go [list -e -json -compiled -test=false -export=false -deps=true -tags=wireinject -- example.com/foo]: exit status 1: go: finding github.com/google/go-cloud v0.2.0
            go build runtime/internal/atomic: failed to cache compiled Go files
```

### To Reproduce

This is an intermittent failure, but I've only seen it on Travis. Uncertain what the triggers are.

## Expected behavior

Wire tests should pass.

/cc @vangent, who I believe hit this failure before, but I can't find evidence of it.

**Comment by dominikh** [comment]
@bcmills with a clean ~/.cache/go-build: https://play.golang.org/p/ghOtMwBnGu7

**Comment by cespare** [comment]
We've been running into this same bug (via staticcheck and other go/packages-using code) in our CI environment as well. I filed https://github.com/golang/go/issues/29667 with @dominikh's helpful reproducer.

**Comment by zombiezen** [comment]
Thank you @dominikh for the clean reproduction, and thank you @cespare for filing the upstream issue. Much appreciated! 👏

**Comment by deafgoat** [comment]
For anyone who might still be running into this, I eventually compiled from the tip of master - where [this commit](https://github.com/golang/go/commit/1dd71645558157f2d4477f21c6e9f18a99b0bc94) - that  includes details in errors from cache operations exists.

Afterwards, I got a new error:
```
go build internal/race: loading compiled Go files from cache: reading srcfiles list: cache entry not found: open /Users/username/Library/Caches/go-build/d7/d7ef4361930d6b215edf518790736afc3772a7c331e4f6e310d5a8022a736a8d-a: no such file or directory
```
Which suggested that the issue might be related to file permissions associated with the `Cache` directory at `/Users/username/Library/Caches/go-build/`.

After running:
```
chown -R $(whoami):admin /Users/username/Library/Caches/go-build
```
I was able to run both `wire` and `go list -compiled=true...` without any errors.

**Comment by cespare** [comment]
@zombiezen the Go bug was fixed for Go 1.13. This shouldn't be happening anymore. (I checked that the repro no longer fails.)

**Comment by deafgoat** [comment]
Interesting. @cespare I ran into the issue when using both Go 1.12 and Go 1.13. Perhaps the cause of the error in my case was different from what others were observing.

**Comment by zombiezen** [comment]
Excellent, thank you! I'll take a look at getting the tests running in parallel again.
