### ISSUE TITLE
wire: generator does not reuse intermediate results

### ISSUE THREAD

**Issue by gracenoah** [google/wire#68]
### Is your feature request related to a problem? Please describe.

Wire takes a very long time to generate code on large projects.

### Describe the solution you'd like

It would be great if wire could be more efficient in cases where it needs to be run multiple times.

### Describe alternatives you've considered

One way might be for it to take a list of packages like `./...` and run against those. Another might be to cache intermediary code inspection results. I don't think that putting all wire files in the same package is feasible because some of them use private functions and structs.

### Additional context

I'm using wire version v0.4.0 573424055b8e657474e034cdb3a8d5f9210010b7

`wire check` takes ~4 seconds.
`wire .` takes ~4 seconds.

We have 6 packages using wire. Soon we'll probable be at closer to 20-30. I'm afraid that it might take 5-10 minutes to run `go generate`.

**Comment by gracenoah** [comment]
I see that support for `./...` has been added in https://github.com/google/go-cloud/pull/729. The latest version of wire takes 17 seconds to generate output in 17 packages using that. That's pretty good for now.

**Comment by zombiezen** [comment]
Excellent, glad this helped. I'll close this out, but feel free to open a new issue if things start getting sluggish again.
