### ISSUE TITLE
Set up Contribute Bot for Wire

### ISSUE THREAD

**Issue by zombiezen** [google/wire#82]
We want to manage Wire with the same set of processes that we developed for Go Cloud. I'll look into making the alterations to Contribute Bot and installing the GitHub application on this repository.

**Comment by zombiezen** [comment]
In thinking about this, what we really want to have is a per-repository configuration on Contribute Bot, of which this is the first divergent property. I briefly considered using runtimevar for this purpose, but the downside would be that the policy would not be version controlled and invisible to those without access to the GCP project. I think the better way would be to have a `.contributebot` JSON file at the top of the repository that stores any configuration policy that we want going forward.

@vangent, does this seem okay?

**Comment by vangent** [comment]
SGTM

**Comment by zombiezen** [comment]
🎉 Contribute Bot is ready to roll! 🎉
