### ISSUE TITLE
Stop permitting old marker functions import path

### ISSUE THREAD

**Issue by zombiezen** [google/wire#83]
For some period of time before removing support, we should add warnings when Wire encounters any code that imports `"github.com/google/go-cloud/wire"` instead of the new `"github.com/google/wire"` import path. I'm not entirely certain of how we want to stage this migration: should it error out, should it only be when a symbol gets used for a provider set versus all dependencies, etc.

**Comment by shantuo** [comment]
Some thoughts:

1.  From go-cloud v0.7.0, people running `wire` from `github.com/google/go-cloud/wire/cmd/wire` get a warning.
2. Remove `wire` from go-cloud v0.7.0, this seems not as good as 1)
3. `github.com/google/wire/cmd/wire` checks for imports from the old repo.

**Comment by zombiezen** [comment]
I think moving the Wire CLI is okay, but if you disagree, we should go discuss over on google/go-cloud#831 where I have a PR that does exactly that. 🙂

**Comment by zombiezen** [comment]
Note that Go Cloud will be moving over to the `gocloud.dev` import paths soon (google/go-cloud#77), so this might be obsoleted by that.

**Comment by zombiezen** [comment]
In reviewing this, I think we can just stop allowing these imports in the next Wire release.
