### ISSUE TITLE
Consider splitting README into multiple docs

### ISSUE THREAD

**Issue by zombiezen** [google/wire#84]
The README is a bit long now, especially now that it contains introductory project material along with user guide and the FAQ section. I think it might be wise to split out the documents, perhaps even using GitHub wiki pages?

**Comment by shantuo** [comment]
I think advanced features and best practices may be moved to wiki pages. The FAQ I'm not sure, I think it can either stay in the README or be moved to its own doc.

**Comment by vangent** [comment]
+1

**Comment by zombiezen** [comment]
GitHub wiki pages don't give the level of access control that seems right for this kind of documentation. But yeah, my idea is four docs:

- README.md
- docs/guide.md (Basics & Advanced Features)
- docs/best-practices.md
- docs/faq.md
